loadash is a dependency required by src/index.js
```
Error: [BABEL]: Cannot find module 'lodash'
Require stack:
- <project>\node_modules\babel-plugin-jsx-auto-test-id\src\index.js
- ...
```